config/routes.rb
MovieApp::Application.routes.draw do
  resources :movies

  root "movies#index"

  

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	validates :title, :description, :year_released, presence: true
  validates :description, length: { minimum: 10 }
  validates :year_released, numericality: { 
  	only_integer: true,
  	greater_than: 0
  } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  	@movies = Movie.all
  end

   def show
  # KH: (remove unused code before committing)
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

# below based on the forms creation guide
  def create
	  @movie = Movie.new(id_params)
	  if @movie.save
  		redirect_to @movie
		else
			render 'new'
		end
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		@movie = Movie.find(params[:id])
		@movie.update_attributes(id_params)

		redirect_to @movie
	end
# for resolving security issues based on guide
private
  # KH: maybe name this movie_params? id_params doesn't make clear what it is/does.
  def id_params
    params.require(:movie).permit(:title, :description, :year_released)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
  <% if @movie.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@movie.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :year_released %><br>
    <%= f.text_field :year_released %>
  </p>  
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render "form" %>

app/views/movies/index.html.erb
<h1>Movies#index</h1>
<p>Welcome to Retflix! See our collection of movies below.</p>

<ul>
<% @movies.each do |x| %>
<li><%=	x.title %> <%= link_to 'Show', movie_path(x) %></li>
<% end %>
</ul>

<%= link_to 'Add a new movie', new_movie_path %>


<p>Find me in app/views/movies/index.html.erb</p>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render "form" %>

app/views/movies/show.html.erb
<!-- I would use the commented out code here instead of the partial.
     since this is a show page, you really should just be able to view (not edit)
     the information.  -->
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Year Released:</strong>
  <%= @movie.year_released %>
</p>

<p>
 <%= link_to 'Index', movies_path %>
</p>